# Olist SQL — Exercises

> **Database:** Olist Brazilian E-Commerce Dataset  
> **Database engine:** SQLite  
> **File expected:** `olist.db`

---

## How to use this notebook

1. Make sure `olist.db` is in the same directory as this notebook.
2. Run the **Setup** cell below once.
3. For each question, write your SQL inside the provided Python cell and run it.
4. You are expected to write the SQL yourself. The questions deliberately progress from one concept to combinations of two or three concepts.

---

## Setup

In [8]:
import os
import sqlite3
import pandas as pd

# Connect to Olist Database
conn = sqlite3.connect("../database/olist.db")

In [11]:
# Create a Helper to Read Database
def run_sql(query):
    return pd.read_sql(query, conn)

In [17]:
run_sql("""
    SELECT * FROM customers LIMIT 5;
""")

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [28]:
run_sql("""
    SELECT * FROM orders LIMIT 5;
""")

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [29]:
run_sql("""
    SELECT * FROM order_items LIMIT 5;
""")

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [21]:
run_sql("""
    SELECT * FROM order_payments LIMIT 5;
""")

                           order_id  payment_sequential payment_type  payment_installments  payment_value
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card                     8          99.33
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card                     1          24.39
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card                     1          65.71
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card                     8         107.78
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card                     2         128.45

In [ ]:
run_sql("""
    SELECT * FROM order_reviews LIMIT 5;
""")

,review_record_id,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,1,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,None,None,2018-01-18 00:00:00,2018-01-18 21:46:59
1,2,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,None,None,2018-03-10 00:00:00,2018-03-11 03:05:13
2,3,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,None,None,2018-02-17 00:00:00,2018-02-18 14:36:24
3,4,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,None,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,5,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,None,Parabéns lojas lannister adorei comprar pela Internet seguro e prático Parabéns a todos feliz Páscoa,2018-03-01 00:00:00,2018-03-02 10:26:53

In [23]:
run_sql("""
    SELECT * FROM products LIMIT 5;
""")

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40,287,1,225,16,10,14
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44,276,1,1000,30,18,20
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46,250,1,154,18,9,15
3,cef67bcfe19066a932b7673e239eb23d,bebes,27,261,1,371,26,4,26
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37,402,4,625,20,17,13

In [24]:
run_sql("""
    SELECT * FROM sellers LIMIT 5;
""")

                          seller_id  seller_zip_code_prefix        seller_city seller_state
0  3442f8959a84dea7ee197c632cb2df15                   13023           campinas           SP
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844         mogi guacu           SP
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031     rio de janeiro           RJ
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195          sao paulo           SP
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914  braganca paulista           SP

In [25]:
run_sql("""
     SELECT * FROM geolocation LIMIT 5;
""")

   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng geolocation_city geolocation_state
0                         1037           -23.55           -46.64        sao paulo                SP
1                         1046           -23.55           -46.64        sao paulo                SP
2                         1046           -23.55           -46.64        sao paulo                SP
3                         1041           -23.54           -46.64        sao paulo                SP
4                         1035           -23.54           -46.64        sao paulo                SP

In [26]:
run_sql("""
    SELECT * FROM product_category_name_translation LIMIT 5;
""")

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

# Part I — JOIN Foundations

## 1. INNER JOIN — Orders and Customers

Return the following for the first 20 orders:

- `order_id`
- `customer_id`
- `customer_city`
- `customer_state`
- `order_status`

Join `orders` to `customers` using the appropriate key.

**Concept:** `INNER JOIN`

In [ ]:
run_sql("""
    SELECT 
        o.order_id,
        o.customer_id,
        c.customer_city,
        c.customer_state,
        o.order_status
    FROM orders AS o
    INNER JOIN customers AS c
        ON o.customer_id = c.customer_id
    LIMIT 20;
""")

,order_id,customer_id,customer_city,customer_state,order_status
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,sao paulo,SP,delivered
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,barreiras,BA,delivered
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,vianopolis,GO,delivered
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,sao goncalo do amarante,RN,delivered
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,santo andre,SP,delivered
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,congonhinhas,PR,delivered
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,santa rosa,RS,invoiced
7,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,nilopolis,RJ,delivered
8,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,faxinalzinho,RS,delivered
9,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,sorocaba,SP,delivered
10,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,rio de janeiro,RJ,delivered
11,34513ce0c4fab462a55830c0989c7edb,7711cf624183d843aafe81855097bc37,sao paulo,SP,delivered
12,82566a660a982b15fb86e904c8d32918,d3e3b74c766bc6214e0c830b17ee2341,ouro preto,MG,delivered
13,5ff96c15d0b717ac6ad1f3d77225a350,19402a48fe860416adf93348aba37740,sao paulo,SP,delivered
14,432aaf21d85167c2c86ec9448c4e42cc,3df704f53d3f1d4818840b34ec672a9f,sao paulo,SP,delivered
15,dcb36b511fcac050b97cd5c05de84dc3,3b6828a50ffe546942b7a473d70ac0fc,goiania,GO,delivered
16,403b97836b0c04a622354cf531062e5f,738b086814c6fcc74b8cc583f8516ee3,rio de janeiro,RJ,delivered
17,116f0b09343b49556bbad5f35bee0cdf,3187789bec990987628d7a9beb4dd6ac,imbituba,SC,delivered
18,85ce859fd6dc634de8d2f1e290444043,059f7fc5719c7da6cbafe370971a8d70,hortolandia,SP,delivered
19,83018ec114eee8641c97e08f7b4e926f,7f8c8b9c2ae27bf3300f670c3d478be8,feira de santana,BA,delivered

## 2. INNER JOIN — Products and Order Items

Return:

- `order_id`
- `product_id`
- `product_category_name`
- `price`

Join `order_items` to `products`.

Return 20 rows.

**Concept:** `INNER JOIN`

In [ ]:
run_sql("""
    SELECT * 
    FROM order_items
    LIMIT 5;
""")

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [48]:
run_sql("""
    SELECT *
    FROM products
    LIMIT 5
""")

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40,287,1,225,16,10,14
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44,276,1,1000,30,18,20
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46,250,1,154,18,9,15
3,cef67bcfe19066a932b7673e239eb23d,bebes,27,261,1,371,26,4,26
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37,402,4,625,20,17,13

In [49]:
run_sql("""
    SELECT
        i.order_id,
        p.product_id,
        p.product_category_name,
        i.price
    FROM order_items AS i
    INNER JOIN products AS p
        ON i.product_id = p.product_id
    LIMIT 20;
""")

                            order_id                        product_id        product_category_name  price
0   00010242fe8c5a6d1ba2dd792cb16214  4244733e06e7ecb4970a6e2683c13e61                   cool_stuff  58.90
1   00018f77f2f0320c557190d7a144bdd3  e5f2d52b802189ee658865ca93d83a8f                     pet_shop 239.90
2   000229ec398224ef6ca0657da4fc703e  c777355d18b72b67abbeef9df44fd0fd             moveis_decoracao 199.00
3   00024acbcdf0a6daa1e931b038114c75  7634da152a4610f1595efa32f14722fc                   perfumaria  12.99
4   00042b26cf59d7ce69dfabb4e55b4fd9  ac6c3623068f30de03045865e4e10089           ferramentas_jardim 199.90
5   00048cc3ae777c65dbb7d2a0634bc1ea  ef92defde845ab8450f9d70c526ef70f        utilidades_domesticas  21.90
6   00054e8431b9d7675808bcb819fb4a32  8d4f2bb7e93e6710a28f34fa83ee7d28                    telefonia  19.90
7   000576fe39319847cbb9d288c5617fa6  557d850972a7d6f792fd18ae1400d9b6           ferramentas_jardim 810.00
8   0005a1a1728c9d785b8e2b08b904576c  310ae3c140ff94b03219ad0adc3c778f                 beleza_saude 145.95
9   0005f50442cb953dcd1d21e1fb923495  4535b0e1091c278dfd193e5a1d63b39f              livros_tecnicos  53.99
10  00061f2a7bc09da83e415a52dc8a4af1  d63c1011f49d98b976c352955b1c4bea                 beleza_saude  59.99
11  00063b381e2406b52ad429470734ebd5  f177554ea93259a5b282f24e33f65ab6  fashion_bolsas_e_acessorios  45.00
12  0006ec9db01a64e59a68b2c340bf65a7  99a4788cb24856965c36a24e339b6058              cama_mesa_banho  74.00
13  0008288aa423d2a3f00fcb17cd7d8719  368c6c730842d78016ad823897a372db           ferramentas_jardim  49.90
14  0008288aa423d2a3f00fcb17cd7d8719  368c6c730842d78016ad823897a372db           ferramentas_jardim  49.90
15  0009792311464db532ff765bf7b182ae  8cab8abac59158715e0d70a36c807415                esporte_lazer  99.90
16  0009c9a17f916a706d71784483a5d643  3f27ac8e699df3d300ec4a5d8c5cf0b2               consoles_games 639.00
17  000aed2e25dbad2f9ddb70584c5a2ded  4fa33915031a8cde03dd0d3e8fb27f01                   perfumaria 144.00
18  000c3e6612759851cc3cbb4b83257986  b50c950aba0dcead2c48032a690ce817                esporte_lazer  99.00
19  000e562887b1f2006d75e0be9558292e  5ed9eaf534f6936b51d0b6c5e4d5c2e9                   cool_stuff  25.00

## 3. LEFT JOIN — Customers With and Without Orders

Return every customer and their order ID.

Show:

- `customer_id`
- `customer_city`
- `customer_state`
- `order_id`

Use a `LEFT JOIN` so that customers who never placed an order are still included.

**Concept:** `LEFT JOIN`

In [55]:
run_sql("""
    SELECT
        c.customer_id,
        c.customer_city,
        c.customer_state,
        o.order_id
    FROM customers AS c
    LEFT JOIN orders AS o
        ON c.customer_id = o.customer_id
    LIMIT 10;
""")

                        customer_id          customer_city customer_state                          order_id
0  06b8999e2fba1a1fbc88172c00ba8bc7                 franca             SP  00e7ee1b050b8499577073aeb2a297a1
1  18955e83d337fd6b2def6b18a428ac77  sao bernardo do campo             SP  29150127e6685892b6eab3eec79f59c7
2  4e7b3e00288586ebd08712fdd0374a03              sao paulo             SP  b2059ed67ce144a36e2aa97d2c9e9ad2
3  b2b6027bc5c5109e529d4dc6358b12c3        mogi das cruzes             SP  951670f92359f4fe4a63112aa7306eba
4  4f2d8ab171c80ec8364f7c12e35b23ad               campinas             SP  6b7d50bd145f6fc7f33cebabd7e49d0f
5  879864dab9bc3047522c92c82e1212b8         jaragua do sul             SC  5741ea1f91b5fbab2bd2dc653a5b5099
6  fd826e7cf63160e536e0908c76c3f441              sao paulo             SP  36e694cf4cbc2a4803200c35e84abdc4
7  5e274e7a0c3809e14aba7ad5aae0d407                timoteo             MG  1093c8304c7a003280dd34598194913d
8  5adf08e34b2e993982a47070956c5c65               curitiba             PR  1ebeea841c590e86a14a0d7a48e7d062
9  4b7139f34592b3a31687243a302fa75b         belo horizonte             MG  7433cbcc783205509d66a5260da5b574

## 4. RIGHT JOIN — Understand the Direction

Rewrite Question 3 using a `RIGHT JOIN` instead of a `LEFT JOIN`.

The result should represent the same relationship.

**Concept:** `RIGHT JOIN` vs `LEFT JOIN`

**Hint:** Think carefully about which table must be on which side of the join.

In [57]:
run_sql("""
    SELECT
        c.customer_id,
        c.customer_city,
        c.customer_state,
        o.order_id
    FROM orders AS o
    RIGHT JOIN customers AS c
        ON c.customer_id = o.customer_id
    LIMIT 10;    
""")

                        customer_id            customer_city customer_state                          order_id
0  9ef432eb6251297304e76186b10a928d                sao paulo             SP  e481f51cbdc54678b7cc49136f2d6af7
1  b0830fb4747a6c6d20dea0b8c802d7ef                barreiras             BA  53cdb2fc8bc7dce0b6741e2150273451
2  41ce2a54c0b03bf3443c3d931a367089               vianopolis             GO  47770eb9100c2d0c44946d9cf07ec65d
3  f88197465ea7920adcdbec7375364d82  sao goncalo do amarante             RN  949d5b44dbf5de918fe9c16f97b45f8a
4  8ab97904e6daea8866dbdbc4fb7aad2c              santo andre             SP  ad21c59c0840e6cb83a9ceb5573f8159
5  503740e9ca751ccdda7ba28e9ab8f608             congonhinhas             PR  a4591c265e18cb1dcee52889e2d8acc3
6  ed0271e0b7da060a393796590e7b737a               santa rosa             RS  136cce7faa42fdb2cefd53fdc79a6098
7  9bdf08b4b3b52b5526ff42d37d47f222                nilopolis             RJ  6514b8ad8028c9f2cc2374ded245783f
8  f54a9f0e6b351c431402b8461ea51999             faxinalzinho             RS  76c6e866289321a7c93b82b54852dc33
9  31ad1d1b63eb9962463f764d4e6e0c9d                 sorocaba             SP  e69bfb5eb88e0ed6a785585b27e16dbf

# Part II — GROUP BY, HAVING, WHERE, ORDER BY

## 5. Count Orders by Status

Return each `order_status` and the number of orders with that status.

Sort from the most common status to the least common status.

**Concepts:** `GROUP BY`, aggregate function, `ORDER BY`

In [61]:
run_sql("""
    SELECT * FROM orders
    LIMIT 5;
""")

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [ ]:
run_sql("""
    SELECT 
        COUNT(order_status)
            AS number_of_status,
            order_status
    FROM orders
    GROUP BY order_status
    ORDER BY number_of_status DESC;
""")

   number_of_status order_status
0             96478    delivered
1              1107      shipped
2               625     canceled
3               609  unavailable
4               314     invoiced
5               301   processing
6                 5      created
7                 2     approved

## 6. Customers With More Than One Order

Find customers who placed more than one order.

Return:

- `customer_id`
- number of orders

Only return customers with more than one order.

**Concepts:** `GROUP BY`, `HAVING`

In [ ]:
run_sql("""
    SELECT 
        customer_id,
    FROM orders
    
    GROUP BY 
""")

## 7. WHERE vs HAVING

Find the number of delivered orders for each customer.

Only consider orders whose status is `delivered`.

Return customers with at least 2 delivered orders.

Return:

- `customer_id`
- delivered order count

**Concepts:** `WHERE` + `GROUP BY` + `HAVING`

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

## 8. Average Product Price by Category

Return each product category and its average product price.

Only include categories whose average product price is greater than 100.

Sort from highest average price to lowest.

**Concepts:** `GROUP BY`, `HAVING`, `ORDER BY`

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

# Part III — Basic Subqueries

## 9. Non-Correlated Subquery — Above-Average Product Price

Find products whose price is greater than the average price of **all products**.

Return:

- `product_id`
- `product_category_name`
- `price`

Sort from most expensive to least expensive.

**Concept:** non-correlated subquery

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

## 10. Subquery with IN

Find all customers who placed at least one order.

Use a subquery with `IN`.

Return:

- `customer_id`
- `customer_city`
- `customer_state`

**Concept:** `IN` + subquery

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

## 11. Subquery with EXISTS

Repeat Question 10, but this time use `EXISTS` instead of `IN`.

Return the same customer information.

**Concept:** `EXISTS` + subquery

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

## 12. Correlated Subquery

Find products whose price is greater than the average price of products in their **own category**.

Return:

- `product_id`
- `product_category_name`
- `price`

**Concept:** correlated subquery

**Hint:** The inner query must refer to the category of the current outer product.

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

# Part IV — Set Operations

## 13. UNION

Create one list containing:

1. customer cities
2. seller cities

Return one column called `city`.

Remove duplicates.

Sort alphabetically.

**Concept:** `UNION`

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

## 14. UNION ALL

Repeat Question 13 using `UNION ALL`.

Do not remove duplicates.

Observe the difference in the number of rows compared with Question 13.

**Concept:** `UNION ALL`

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

## 15. INTERSECT

Find cities that appear in both:

- the customer table
- the seller table

Return one column called `city`.

Sort alphabetically.

**Concept:** `INTERSECT`

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

## 16. EXCEPT

Find cities that appear among customers but do not appear among sellers.

Return one column called `city`.

Sort alphabetically.

**Concept:** `EXCEPT`

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

# Part V — Outer Joins and NULL

## 17. Customers Without Orders

Find customers who have never placed an order.

Use a `LEFT JOIN`.

Return:

- `customer_id`
- `customer_city`
- `customer_state`

**Do not use a subquery.**

**Concepts:** `LEFT JOIN`, `NULL`, filtering unmatched rows

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

## 18. Products That Have Never Been Ordered

Find products that do not appear in `order_items`.

Return:

- `product_id`
- `product_category_name`

Use a `LEFT JOIN`.

**Concepts:** `LEFT JOIN`, `NULL`

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

## 19. FULL OUTER JOIN — Understand Unmatched Rows

Create a simple comparison between customer cities and seller cities using a `FULL OUTER JOIN`.

Return:

- customer city
- seller city

You are not required to produce a meaningful business report. The purpose is to observe what happens when rows exist on one side but not the other.

**Concept:** `FULL OUTER JOIN`

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

# Part VI — NATURAL JOIN

## 20. NATURAL JOIN — Why It Can Be Dangerous

Use a `NATURAL JOIN` between two suitable Olist tables that share a column name.

Then write the equivalent explicit `JOIN ... ON ...` query.

Compare the results.

In your answer, explain:

1. Which columns SQLite used automatically.
2. Why explicitly naming the join condition is safer in production SQL.
3. What could happen if a new column with the same name were later added to both tables.

**Concept:** `NATURAL JOIN`, implicit join keys, maintainability risk

In [ ]:
# NATURAL JOIN version
query_natural = """
-- Write your NATURAL JOIN SQL here

"""

print("=== NATURAL JOIN ===")
display(pd.read_sql_query(query_natural, conn))

# Explicit JOIN version
query_explicit = """
-- Write the equivalent explicit JOIN ... ON ... here

"""

print("\n=== Explicit JOIN ===")
display(pd.read_sql_query(query_explicit, conn))

# Part VII — Logical Query Processing

## 21. Explain the Processing Order

Consider:

```sql
SELECT
    c.customer_state,
    COUNT(*) AS order_count
FROM customers AS c
JOIN orders AS o
    ON c.customer_id = o.customer_id
WHERE o.order_status = 'delivered'
GROUP BY c.customer_state
HAVING COUNT(*) >= 1000
ORDER BY order_count DESC
LIMIT 5;
```

Without executing it, explain what each stage is doing.

Use this conceptual order:

- FROM
- JOIN / ON
- WHERE
- GROUP BY
- HAVING
- SELECT
- ORDER BY
- LIMIT

Then explain why WHERE filters individual rows while HAVING filters groups.

**Concept:** logical query processing order

> Write your explanation in a markdown cell below or as comments.

In [ ]:
# Optional: run the query to verify your understanding
query = """
SELECT
    c.customer_state,
    COUNT(*) AS order_count
FROM customers AS c
JOIN orders AS o
    ON c.customer_id = o.customer_id
WHERE o.order_status = 'delivered'
GROUP BY c.customer_state
HAVING COUNT(*) >= 1000
ORDER BY order_count DESC
LIMIT 5;
"""

pd.read_sql_query(query, conn)

# Part VIII — Integrated but Still Manageable

## 22. Customer Order Summary

Create a report containing:

- `customer_id`
- `customer_city`
- total number of orders

Include every customer, including customers with zero orders.

Sort by total orders from highest to lowest.

**Concepts:** `LEFT JOIN`, `GROUP BY`, `ORDER BY`

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

## 23. Category Sales Summary

Join `order_items` to `products`.

Calculate the total item revenue for each product category using:

`price × order_item quantity`

> **Note for Olist:** The real Olist `order_items` table does **not** have a quantity column.  
> Each row already represents one item. Use `SUM(price)` (or `SUM(price * 1)` conceptually).

Return:

- product category
- total revenue

Sort from highest revenue to lowest.

**Concepts:** `INNER JOIN`, arithmetic, `GROUP BY`, `ORDER BY`

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

## 24. High-Value Customers

Find customers whose total order-item spending is greater than 1,000.

Return:

- `customer_id`
- total spending

Only include customers above 1,000.

Sort from highest spending to lowest.

**Concepts:** multiple joins, `GROUP BY`, `HAVING`, `ORDER BY`

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

# Part IX — Final Week 2 Challenge

## 25. Customers Who Bought Above-Average-Priced Products

Find customers who purchased at least one product whose price is greater than the average product price across the entire products table.

Return:

- `customer_id`
- `customer_unique_id`

Do not return duplicate customers.

**Recommended approach:** combine a basic subquery with straightforward joins.

Do not use CTEs or window functions.

**Concepts:** subquery, `INNER JOIN`, `DISTINCT`

In [ ]:
query = """
-- Write your SQL here

"""

pd.read_sql_query(query, conn)

---

## Coverage Checklist

Before considering Week 2 complete, you should have personally solved:

- [ ] INNER JOIN
- [ ] LEFT JOIN
- [ ] RIGHT JOIN
- [ ] FULL OUTER JOIN
- [ ] NATURAL JOIN
- [ ] WHERE
- [ ] GROUP BY
- [ ] HAVING
- [ ] ORDER BY
- [ ] IN
- [ ] EXISTS
- [ ] non-correlated subquery
- [ ] correlated subquery
- [ ] UNION
- [ ] UNION ALL
- [ ] INTERSECT
- [ ] EXCEPT
- [ ] NULL handling with outer joins
- [ ] logical query processing order
- [ ] combining joins with aggregation
- [ ] combining a subquery with a join

---

**Tip:** After finishing, you can close the connection with:

```python
conn.close()
```

In [ ]:
# Optional: close the connection when finished
# conn.close()